Revert "Merge pull request #20 from rolandlo/update-to-1.0.20"
This reverts commit bc6014799ddfa04316a40dae4e233ef793703fac, reversing
changes made to 42adcd529693710a842c5348ef35e9cbf6eae20d.

This is due to a bug report:
https://github.com/flathub/com.github.xournalpp.xournalpp/issues/21

The app wouldn't start with the TexLive extension installed:

$ flatpak run com.github.xournalpp.xournalpp
bwrap: Can't mkdir /app/extensions: Read-only file system
error: ldconfig failed, exit status 256
$